package org.lowScore;

import br.com.nutriscare.nutrisCareRulesApi.entity.User;
import br.com.nutriscare.nutrisCareRulesApi.entity.HealthUsu;
import br.com.nutriscare.nutrisCareRulesApi.entity.Diet;

rule "Low Score"
    when
        $user : HealthUsu(id != null)
    then
        Diet diet = new Diet();
        diet.setUsuId($user.getId());
        diet.setCarboPercentage(55.0);
        diet.setProteinPercentage(25.0);
        diet.setLipidPercentage(20.0);

        insert(diet);
end
